# Generated by Django 5.2.17 on 2026-09-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=64, unique=True)),
                ("provider", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                (
                    "input_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("latency_ms", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        max_length=10,
                    ),
                ),
                ("error_category", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_usages",
                        to="accounts.apikey",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
